@baseUrl = http://localhost:3001/api

### 1. Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "test1",
    "email": "test1examaple.com",
    "password": "password123"
    
}

### 2. Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
    
}

### 3. Get Current User (Using token from login)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.$.data.token}}