@startuml c4
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

left to right direction

LAYOUT_WITH_LEGEND()

Person(user, "User", "Concord user")

System_Boundary(discord_clone, "Concord") {
    Container(web_app, "Web Application", "React", "Provides Concord UI via browser")
    Container(api, "API Application", "NestJS", "Handles business logic, authentication, real-time messaging")
    ContainerDb(db, "Database", "PostgreSQL", "Stores users, servers, channels, messages")
}

Rel(user, web_app, "Uses", "HTTPS")
Rel(web_app, api, "Makes API calls to", "HTTPS/WSS")
Rel(api, db, "Reads from and writes to", "TCP/IP")

@enduml