@startuml der_simplificado

!theme plain
hide circle
skinparam linetype ortho
left to right direction
skinparam nodesep 120
skinparam ranksep 140

entity "users" as users {
  *id : UUID <<PK>>
  --
  *username : VARCHAR
  *email : VARCHAR
  *password_hash : VARCHAR
  avatar_url : VARCHAR
}

entity "rooms" as rooms {
  *id : UUID <<PK>>
  --
  name : VARCHAR (null para DMs)
  is_group : BOOLEAN (true=canal, false=DM)
  created_at : TIMESTAMP
}

entity "room_members" as room_members {
  *room_id : UUID <<PK, FK>>
  *user_id : UUID <<PK, FK>>
  --
  joined_at : TIMESTAMP
}

entity "messages" as messages {
  *id : UUID <<PK>>
  --
  *room_id : UUID <<FK>>
  *user_id : UUID <<FK>>
  *content : TEXT
  created_at : TIMESTAMP
}

users ||..o{ room_members : "participa"
rooms ||..o{ room_members : "tem"
rooms ||--o{ messages : "contêm"
users ||--o{ messages : "envia"

@enduml