@startuml usecase_simplificado

left to right direction

actor "Usuário" as user
actor "Visitante" as guest

rectangle "Team Communicator" {
    usecase "Cadastrar/Login" as UC1
    usecase "Criar Canal (Grupo)" as UC2
    usecase "Enviar Mensagem" as UC3
    usecase "Iniciar Conversa Direta" as UC4
    usecase "Listar Membros" as UC5
}

guest --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5

@enduml